
export const GET_IMAGES = "GET_IMAGES"; 
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS"; 
export const GET_IMAGES_FAILURE = "GET_IMAGES_FAILURE"; 
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS"; 
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE"; 
